# Generated by Django 5.0.7 on 2024-07-23 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
