# Generated by Django 5.0.7 on 2024-07-31 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_lastname_author_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='categorias',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='fecha_creado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
